config/routes.rb
Todolist::Application.routes.draw do

  get "users/create"
  get "users/update"
  root 'index#index', as: 'index'
  controller :index do
    get     '/' => :index
    post    '/' => :create
    patch   '/' => :update
    delete  '/' => :destroy
  end
  
  controller :needs do
    get     ':user_name' => :index
    post    ':user_name' => :create, as: 'new_need'
    patch   ':user_name' => :update, as: 'edit_need'
    delete  ':user_name' => :destroy, as: 'destroy_need'
  end

  

end

app/models/need.rb
class Need < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  # GET /
  # GET /
  def index
    if session[:user_id]
      redirect_to "/#{session[:user_name]}"
    else
      session[:needs] ||= {}
      @needs = session[:needs].sort {|a,b| b[0]<=>a[0]} #Need.all
    end
  end

  # POST /
  # POST /
  def create
    unless params[:text].empty?
      date = Time.now
      session[:needs].merge!( { "#{date.to_i}" =>
        {text: params[:text], date: date.strftime("%m.%d.%Y %H:%M"),
        competed: false} })
    end
    
    respond_to do |format|
        format.js { @need = session[:needs]["#{date.to_i}"], date.to_i }
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    @need = {date: params[:date]}
    if params[:complete] == 'true'
      need_state = session[:needs][params[:date]][:completed]
      session[:needs][params[:date]][:completed] = need_state ? false : true
      @need[:completed] = need_state ? 'false' : 'true'
    else
      session[:needs][params[:date]][:text] = params[:text] unless params[:text].empty?
      @need[:text] = session[:needs][params[:date]][:text]
    end
    
    respond_to do |format|
        format.js { @need }
    end
  end

  # DELETE /1
  # DELETE /1.json
  def destroy
    session[:needs].delete(params[:date])
    
    respond_to do |format|
      format.js { @date = params[:date] }
    end
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_action :set_need, only: [:show, :edit, :update, :destroy]

  # GET /needs
  # GET /needs.json
  def index
    @needs = Need.all
  end

  # GET /needs/1
  # GET /needs/1.json
  def show
  end

  # GET /needs/new
  def new
    @need = Need.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create
    @need = Need.new(need_params)

    respond_to do |format|
      if @need.save
        format.html { redirect_to @need, notice: 'Need was successfully created.' }
        format.json { render action: 'show', status: :created, location: @need }
      else
        format.html { render action: 'new' }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    respond_to do |format|
      if @need.update(need_params)
        format.html { redirect_to @need, notice: 'Need was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to needs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need
      @need = Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_params
      params.require(:need).permit(:text, :completed, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/_form.html.erb
<%= form_tag("/", method: :post, id: "new_need") do %>
  <div class="field" style='float:left'>
    <%= text_field_tag :text, "", options = {size: "30", id: "need_text"}%>
  </div>
  <div class="actions">
    <%= submit_tag "Добавить" %>
  </div>
<% end %>

app/views/index/create.js.erb
<% $stderr<< @need %>
$('#need_text').val("")
$('#needs').prepend("<div class='item' id='<%= @need[1] %>'></div>")
$('#<%= @need[1] %>').html("<div class='info'><%= @need[0][:date] %>: </div>\
  <div class='text' contenteditable spellcheck='false'><%= @need[0][:text] %></div>\
  <span class='shadow'><%= @need[0][:text] %></span>" +
  '<div class="controls">\
    <%= link_to '', '#', class: 'delete_need' %>\
    <%= link_to '', '#', class: 'complete_need' %>\
  </div>')
$('#<%= @need[1] %>').settings()

app/views/index/destroy.js.erb
$('#<%= @date %>').remove()

app/views/index/index.html.erb
<h1>Список дел</h1>

<div id="new_need">
  <textarea id="need_text"></textarea>
  <a id="add" href="#"></a>
</div>

<div id='needs'>
    <% @needs.each do |date, need| %>
      <div class='item <%= "completed" if need[:completed] %>' id='<%= date %>'>  
        <div class='info'><%= need[:date] %>: </div>
        <div class='text' spellcheck='false'<%= "contenteditable" unless need[:completed]%>><%= need[:text].gsub(/\\n/, "\n") %></div>
        <span class='shadow'><%= need[:text].gsub(/\\n/, "\n") %></span>
        <div class='controls'>
          <%= link_to '', '#', class: 'delete_need' %>
          <%= link_to '', '#', class: 'complete_need' %>
        </div>
      </div>
    <% end %>
</div>

<div id='buffer'></div>

app/views/index/update.js.erb
item = $('#<%= @need[:date] %>')
<% if @need[:completed] == 'true' %>
  item.addClass('completed').find('.text').attr('contenteditable', 'false')
  $('#need_text').focus()
<% elsif @need[:completed] == 'false' %>
  item.removeClass('completed').find('.text').attr('contenteditable', 'true')
<% else %>
  item.find('.text').html("<%= @need[:text] %>")
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
</head>
<body>
  <div id="main">
    <%= yield %>
  </div>
  <footer>
    <div id="hints">
      <p>Для изменения текста задания нажмите на него</p>
      <p>Для сохранения изменений нажмите Enter или просто кликните на пустое пространство</p>
      <p>Нажмите на галочку, чтобы пометить задание завершённым</p>
    </div>
    <div id='copyright'>&copy; Дмитрий Краснов, 2014</div>
  </footer>
</body>
</html>

app/views/needs/_form.html.erb
<%= form_for(@need) do |f| %>
  <% if @need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>

      <ul>
      <% @need.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/needs/edit.html.erb
<h1>Editing need</h1>

<%= render 'form' %>

<%= link_to 'Show', @need %> |
<%= link_to 'Back', needs_path %>

app/views/needs/index.html.erb
<h1>Listing needs</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Completed</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @needs.each do |need| %>
      <tr>
        <td><%= need.text %></td>
        <td><%= need.completed %></td>
        <td><%= need.user_id %></td>
        <td><%= link_to 'Show', need %></td>
        <td><%= link_to 'Edit', edit_need_path(need) %></td>
        <td><%= link_to 'Destroy', need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Need', new_need_path %>

app/views/needs/new.html.erb
<h1>New need</h1>

<%= render 'form' %>

<%= link_to 'Back', needs_path %>

app/views/needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @need.text %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @need.completed %>
</p>

<p>
  <strong>User:</strong>
  <%= @need.user_id %>
</p>

<%= link_to 'Edit', edit_need_path(@need) %> |
<%= link_to 'Back', needs_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>